### PR TITLE
update decode dependency

### PR DESCRIPTION
**Pull request by zoeyang7633**

### CODE REVIEW

**Comment by ender336** [comment]
I see an old version referenced in C:\src\client\clarity\package.json

**Comment by ender336** [comment]
>     "clarity-js": "^0.7.29"

update

---
Refers to: packages/clarity-decode/package.json:29 in 6487d75. [](commit_id = 6487d75958626628bfb17f99dea0c00436fcb52a, deletion_comment = False)

**Comment by ender336** [comment]
devtools package.json has 3 references to 0.7.29 that need updating as well

**Review by ender336 — APPROVED** [review]
:shipit:

**Review by keyrun — APPROVED** [review]

**Pull request merged**
