### PR TITLE
Support for single page applications

### PR DESCRIPTION
**Pull request by sarveshnagpal**
Listen to change in history API to auto determine page boundaries within single page application.

### CODE REVIEW

**Review by swaathee — APPROVED** [review]
:shipit:

**Comment by danlaunchcontrol** [comment]
Note, my angular SPA app broke after this change, I get a chrome 'Page Unresponsive' It doesn't break right away, but after a few actions in our app, it happens every time and is predicable. No code change on our part.

**Comment by sarveshnagpal** [comment]
> Note, my angular SPA app broke after this change, I get a chrome 'Page Unresponsive' It doesn't break right away, but after a few actions in our app, it happens every time and is predicable. No code change on our part.

Sorry to hear that @danlaunchcontrol - is it the same link you shared earlier that is behind the login? Is there any debug info that you are able to get from dev tools or share a repro steps that might help us investigate what might be the root cause. 

Few actions which lead to unresponsiveness - do they also involve update the URL using pushState / replaceState? Thanks.

**Comment by danlaunchcontrol** [comment]
> > Note, my angular SPA app broke after this change, I get a chrome 'Page Unresponsive' It doesn't break right away, but after a few actions in our app, it happens every time and is predicable. No code change on our part.
> 
> Sorry to hear that @danlaunchcontrol - is it the same link you shared earlier that is behind the login? Is there any debug info that you are able to get from dev tools or share a repro steps that might help us investigate what might be the root cause.
> 
> The actions that lead to unresponsiveness - do they involve updating the URL using pushState / replaceState? Thanks.

The console is empty doesn't show anything and the browser becomes unresponsive. There is no URL change on that action though. That part does use Websockets and SignalR, that section differs in that way.

**Comment by sarveshnagpal** [comment]
> > > Note, my angular SPA app broke after this change, I get a chrome 'Page Unresponsive' It doesn't break right away, but after a few actions in our app, it happens every time and is predicable. No code change on our part.
> > 
> > 
> > Sorry to hear that @danlaunchcontrol - is it the same link you shared earlier that is behind the login? Is there any debug info that you are able to get from dev tools or share a repro steps that might help us investigate what might be the root cause.
> > The actions that lead to unresponsiveness - do they involve updating the URL using pushState / replaceState? Thanks.
> 
> The console is empty doesn't show anything and the browser becomes unresponsive. There is no URL change on that action though. That part does use Websockets and SignalR, that section differs in that way.

Thanks @danlaunchcontrol for the additional info. Unfortunately, I wasn't able to repro yet. Would it be possible to temporarily give access to your application for the purposes of debugging? Understand if not possible but if you have a concept of test account - please send an email it to clarityms AT microsoft.com and I can take it from there.

**Comment by danlaunchcontrol** [comment]
> > > > Note, my angular SPA app broke after this change, I get a chrome 'Page Unresponsive' It doesn't break right away, but after a few actions in our app, it happens every time and is predicable. No code change on our part.
> > > 
> > > 
> > > Sorry to hear that @danlaunchcontrol - is it the same link you shared earlier that is behind the login? Is there any debug info that you are able to get from dev tools or share a repro steps that might help us investigate what might be the root cause.
> > > The actions that lead to unresponsiveness - do they involve updating the URL using pushState / replaceState? Thanks.
> > 
> > 
> > The console is empty doesn't show anything and the browser becomes unresponsive. There is no URL change on that action though. That part does use Websockets and SignalR, that section differs in that way.
> 
> Thanks @danlaunchcontrol for the additional info. Unfortunately, I wasn't able to repro yet. Would it be possible to temporarily give access to your application for the purposes of debugging? Understand if not possible but if you have a concept of test account - please send an email it to clarityms AT microsoft.com and I can take it from there.

Sorry right now I can't set that up. Have to take it out of our code in this app, so it's not there anymore anyway. It did come from https://aspnetzero.com/ template though

**Comment by maxvin** [comment]
Hello, I am experience the same problem as well. I have opened issue for this. It very critical, for now we need to disable clarity on all our sites (

**Comment by sarveshnagpal** [comment]
> Hello, I am experience the same problem as well. I have opened issue for this. It very critical, for now we need to disable clarity on all our sites (

Thanks @maxvin for reporting. Thanks to @danlaunchcontrol - I was able to repro issue at least one one sample Angular application and believe the issue is related to how Zone.js overrides MutationObserver API. While I dig deeper - I've released a mitigation PR to ensure there's no live site impact for you folks. See #79.

**Comment by k-tokitoh** [comment]
Same as my Next.js application. Stack trace is as follows.
```
react_devtools_backend.js:2430 TypeError: Cannot read property 'apply' of null
    at CSSStyleSheet.deleteRule (VM201 clarity.js:2)
    at e.c.replaceRule (6c7ed4d9c7b9c76f9d77cdd3ca0f1c1b178acee7.a585b96b875d7febd22c.js:1)
    at e.c.deleteRule (6c7ed4d9c7b9c76f9d77cdd3ca0f1c1b178acee7.a585b96b875d7febd22c.js:1)
    at 6c7ed4d9c7b9c76f9d77cdd3ca0f1c1b178acee7.a585b96b875d7febd22c.js:1
    at Array.forEach (<anonymous>)
    at e.t.remove (6c7ed4d9c7b9c76f9d77cdd3ca0f1c1b178acee7.a585b96b875d7febd22c.js:1)
    at n.i.componentWillUnmount (6c7ed4d9c7b9c76f9d77cdd3ca0f1c1b178acee7.a585b96b875d7febd22c.js:1)
    at framework.23418682291b7dbc3fd6.js:1
    at aa (framework.23418682291b7dbc3fd6.js:1)
    at fa (framework.23418682291b7dbc3fd6.js:1)
```

**Comment by sarveshnagpal** [comment]
> Same as my Next.js application. Stack trace is as follows.
> 
> ```
> react_devtools_backend.js:2430 TypeError: Cannot read property 'apply' of null
>     at CSSStyleSheet.deleteRule (VM201 clarity.js:2)
>     at e.c.replaceRule (6c7ed4d9c7b9c76f9d77cdd3ca0f1c1b178acee7.a585b96b875d7febd22c.js:1)
>     at e.c.deleteRule (6c7ed4d9c7b9c76f9d77cdd3ca0f1c1b178acee7.a585b96b875d7febd22c.js:1)
>     at 6c7ed4d9c7b9c76f9d77cdd3ca0f1c1b178acee7.a585b96b875d7febd22c.js:1
>     at Array.forEach (<anonymous>)
>     at e.t.remove (6c7ed4d9c7b9c76f9d77cdd3ca0f1c1b178acee7.a585b96b875d7febd22c.js:1)
>     at n.i.componentWillUnmount (6c7ed4d9c7b9c76f9d77cdd3ca0f1c1b178acee7.a585b96b875d7febd22c.js:1)
>     at framework.23418682291b7dbc3fd6.js:1
>     at aa (framework.23418682291b7dbc3fd6.js:1)
>     at fa (framework.23418682291b7dbc3fd6.js:1)
> ```

Thanks @k-tokitoh for reporting and including the stack trace. That helps. Is your website publicly accessible by any chance? If so, can you please share a URL to it - that will help me validate a fix. Thanks.

**Comment by k-tokitoh** [comment]
Sorry, on public one we have just stopped clarity integration and errors do not happen now.

**Comment by sarveshnagpal** [comment]
@danlaunchcontrol & @maxvin - when you get a chance, could you please help validate the fix by injecting Clarity tag on your pages again (even in dev/staging env) and see if the error has gone away? 0.6.1 is deployed and you should automatically get the updated bits where the original issue was resolved. Thanks.

**Comment by maxvin** [comment]
@sarveshnagpal Checked with version 0.6.1 - works ok! Thank you!

**Pull request merged**
